include:
  project: gardenlinux/gardenlinux-package-build
  file: pipeline/pipeline.yml

variables:
  SOURCE_NAME: ferm
#  SOURCE_REPO: https://github.com/MaxKellermann/ferm
#  SOURCE_TAG_PREFIX: v
  BUILD_ARCH_ALL: 'true'
